name: effective_rick_and_morty
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  auto_route: ^10.0.1
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0

  cupertino_icons: ^1.0.8
  data:
    path: data
  dio: ^5.8.0+1
  domain:
    path: domain
  extended_image: ^10.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.1.0
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  intl: ^0.20.2
  logger: ^2.5.0
  provider: ^6.1.5
  retrofit: ^4.4.2

dev_dependencies:
  auto_route_generator: ^10.0.1
  bloc_test: ^10.0.0
  build_runner: ^2.4.15

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  integration_test:
    sdk: flutter
  mockito: ^5.4.6

flutter:
  uses-material-design: true

  assets:
    - .env
flutter_intl:
  enabled: true
